# Generated by Django 3.1.5 on 2021-02-01 19:28

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210122_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
