# Generated by Django 3.1.5 on 2021-02-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210203_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='full_path_category',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
